config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :edit, :update]

  resource :session, only:[:new, :create, :destroy]

  get '/password', to: 'users#edit_password', as: :edit_password
  post '/password', to: 'users#update_password', as: :update_password

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      can :manage, :all 
   end

    alias_action :create, :read, :update, :delete, to: :crud

    can :crud, Post do |post|
      user == post.user
    end
 
    can :crud, Comment do |comment|
      user == comment.user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user
    
    validates :title, presence: { message: "must be provided" }, uniqueness: true
    validates :body, presence: true, length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :posts, dependent: :nullify
    has_many :comments, dependent: :nullify

    validates :email, email: true
    # bundle gem 'email_validator', '~> 2.2', '>= 2.2.3'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
      helper_method :current_user
  
    def user_signed_in?
        current_user.present?
    end
      helper_method :user_signed_in?
      
    def authenticate_user!
        redirect_to root_path, notice: "Please sign in" unless user_signed_in?
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post
    before_action :authenticate_user!

    def create
        @comment = Comment.new(params.require(:comment).permit(:body)) 
        @comment.post = @post 
        @comment.user = current_user
        if @comment.save
          redirect_to post_path(@post), notice: "Comment created!"
        else
          @comments = @post.comments.order(created_at: :desc)
          render '/posts/show', status: 303
        end       
    end

    def destroy
        @comment = Comment.find(params[:id])
        if can?(:crud, @comment)
          @comment.destroy
          redirect_to post_path(@post), notice: "Comment deleted successfully!"
        else
          redirect_to root_path, alert: "Not authorized" 
        end
    end

    private

    def find_post
        @post = Post.find params[:post_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only:[:edit, :update, :destroy]
  
  # =============CREATE========================
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post created successfully!"
      redirect_to post_path(@post)
    else
      render :new
      flash[:notice]= "Body must have more than 50 characters"
    end
  end

  # ================READ========================
  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # ===============EDIT==========================
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else 
      render :edit
    end
  end

  # ================DELETE=========================
  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @post)
  end

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
  
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, {notice: "Logged In"}
    else
      render :new, {alert: "Wrong email or password!", status: 303}
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash.notice = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :edit_password, :update_password]
    before_action :authenticate_user!, only: [:edit, :update, :edit_password, :update_password]

    def new
        @user = User.new
    end
    def create
        @user = User.new params.require(:user).permit(
          :name,
          :email,
          :password,
          :password_confirmation
        )

        if @user.save
            session[:user_id] = @user.id
            flash.notice = "Signed up!"
            redirect_to root_path
        else
            render :new, status: 303
        end
    end

    # ===============EDIT==========================
    def edit
    end

    def update
        if @user.update(user_params)
        redirect_to root_path, { status: 303, notice: 'User profile updated successfully' }
        else 
        render :edit, status: 303
        end
    end
    # ===============EDIT PASSWORD==========================
    def edit_password
    end

    def update_password
        if params[:new_password] != params[:current_password]
            if params[:new_password] == params[:new_password_confirmation]
              if @user&.authenticate params[:current_password]
                if @user&.update password: params[:new_password], password_confirmation: params[:new_password_confirmation]
                  redirect_to root_path, { status: 303, notice: 'Password updated successfully' }
                else
                  flash.now[:alert] = @user.errors.full_messages.join(', ')
                  render :edit_password, status: 303
                end
              else
                flash.now[:alert] = 'Current password wrong'
                render :edit_password, status: 303
              end
            else
              flash.now[:alert] = 'New password does not match'
              render :edit_password, status: 303
            end
        else
            flash.now[:alert] = 'New password cannot be the same as your current password'
            render :edit_password, status: 303
        end
    end

    private

    def find_user
        @user = current_user
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <header>
      <nav>
      </nav>
      <nav class="navbar navbar-light bg-light">
        <div class="nav-container"> 
          <a class="text-primary navbar-brand" href="<%= root_path %>" style="margin-left: 1em">Blog on Rails</a>
        </div>
        <div class="nav-items-set justify-content-end">
          <ul class="nav">

            <li class="nav-item active">
              <a class="text-primary nav-link" href="<%= root_path %>">Home</a>
            </li>
            <li class="nav-item">
              <a class="text-primary nav-link" href="<%= new_post_path %>">New Post</a>
            </li>

            <% if(user_signed_in?) %>
              <li class="nav-item">
                <a class="nav-link" href="<%= edit_user_path(current_user) %>"><%= current_user.name %> </a>
              </li>
              <li class="nav-item">
                <div><%= button_to "Log out", session_path, method: :delete, class: "btn btn-danger" %></div>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header> 
    <div>
      <% flash.each do |type, message| %>
        <div class="alert alert-info" role="alert">
          <%= type + "------" + message %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="m-3">
    <%= form_with(model: @post) do |form| %>
        <div class= "mt-4">
            <%= form.label :title%>
            <br>
            <%= form.text_field :title, class: "form-control my-2" %>
        </div>
        <div class = "mt-3">
            <%= form.label :body %>
            <br>
            <%= form.text_area :body, class: "form-control mt-2 mb-3" %>
        </div>
        <%= form.submit @button_text, class: "btn btn-outline-primary" %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<div class="container-flex">
    <div class="d-flex flex-row justify-content-around flex-wrap m-1">
        <% @posts.each do |post| %>
            <div class="card my-3" style="width: 25rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-decoration-none" %></h5>
                    <p class="card-text"><%=post.body.truncate(50)%></p>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="m-3">
  <h1><%= @post.title %></h1>
  <p><%= @post.body %></p>

  <p><small>Posted <%= time_ago_in_words(@post.created_at) %> ago</small> | 
  <small>Created by: <%= @post.user.name %></small></p>
  
  <% if can? :crud, @post %>
  <div class="btn-toolbar mt-2" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group me-2" role="group">
      <%= button_to 'Edit', edit_post_path(@post), method: :get, class:"btn btn-outline-primary mb-3" %>
    </div>
    <div class="btn-group" role="group">
    <%= button_to 'Delete', post_path(@post), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class:"btn btn-outline-primary mb-3"  %>
    </div>
  </div>
  <% end %>

  <h3>Comment</h3>
  <% if @comment.errors.any? %>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with(model:[@post, @comment]) do |f| %>
    <div>
      <%= f.text_area :body, class: "form-control mb-3", placeholder:"What's on your mind?"  %>
    </div>
    <%= f.submit "Submit", class: "btn btn-outline-primary mb-4" %>
  <% end %>

  <div>
      <% @comments.each do |comment| %>
          <div><%= comment.body %>
          <div class="d-flex mb-1">
          <small class="d-flex align-items-center">Commented <%= time_ago_in_words(comment.created_at) %> ago by: <label><%= comment.user.name %></label></small>
          <% if can? :crud, comment %>
            <span class="dot mx-1"> • </span>
            <%= button_to "Delete", post_comment_path(@post, comment), method: :delete,form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-link my-1 p-0 border-0 text-decoration-none", style:"font-size: 14px;" %>
          <% end %>
          </div>
          </div>
      
      <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="m-3">
    <h1>Your Account Details</h1>

    <% if @user.errors.any? %>
        <p><%= @user.errors.full_messages.join(', ') %> </p>
    <% end %>

    <%= form_with model: @user do |f| %>
        <div>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control my-1", required: :required %>
        </div>
        <div>
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control my-1", required: :required %>
        </div>
        <%= f.submit "Update Profile", class:"btn btn-outline-primary px-4 my-3" %>
    <% end %>

    <%= button_to 'Change Password', edit_password_path, method: :get, class:"btn btn-outline-primary mb-3" %>
</div>

app/views/users/edit_password.html.erb
<div class="m-3">
<h1>Change Password</h1>
<%= form_with url: update_password_path, method: :post do |f| %>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password, class:"form-control", required: true %>
  </div>
  <div>
    <%= f.label :new_password %>
    <%= f.password_field :new_password, class: "form-control", required: :required %>
  </div>
  <div>
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :new_password_confirmation, class: "form-control", required: :required %>
  </div>
  <%= f.submit "Update Password", class:"btn btn-outline-primary px-4 my-2" %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="m-3">
  <h1>Sign Up</h1>

  <% if @user.errors.any? %>
    <p><%= @user.errors.full_messages.join(', ') %> </p>
  <% end %>


  <%= form_with model: @user do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: :required %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", required: :required %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", required: :required %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", required: :required %>
    </div>
    <%= f.submit "Sign up", class: "btn btn-outline-primary my-2" %>
  <% end %>
</div>